name: 'App Center Distribution for free'
description: 'Distribute app to testers and users using App Center'
author: 'tomisacat <wajmjjj@gmail.com>'
inputs:
  appName:
    description: 'App name followed by username e.g. tomisacat/Sample-App'
    required: true
  token:
    description: "Upload token - you can get one from appcenter.ms/settings"
    required: true
  group:
    description: "Distribution group"
    required: true
  file:
    description: "Artefact to upload (.apk or .ipa)"
    required: true
  buildVersion:
    description: "Build version parameter required for .zip, .msi, .pkg and .dmg files"
    required: false
  buildNumber:
    description: "Build number parameter required for macOS .pkg and .dmg files"
    required: false
  releaseNotes:
    description: "Release notes visible on release page"
    required: false
  gitReleaseNotes:
    description: "Generate release notes based on the latest git commit"
    required: false
  notifyTesters:
    description: "If true, send an email notification to the distribution group"
    required: false
  debug:
    description: "If true, shows additional information from the action execution"
    required: false
    default: false
branding:
  color: "red"
  icon: "send"
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: |
        export INPUT_APPNAME=${{ inputs.appName }}
        export INPUT_TOKEN=${{ inputs.token }}
        export INPUT_GROUP=${{ inputs.group }}
        export INPUT_FILE=${{ inputs.file }}
        export INPUT_BUILDVERSION=${{ inputs.buildVersion }}
        export INPUT_BUILDNUMBER=${{ inputs.buildNumber }}
        export INPUT_RELEASENOTES=${{ inputs.releaseNotes }}
        export INPUT_GITRELEASENOTES=${{ inputs.gitReleaseNotes }}
        export INPUT_NOTIFYTESTERS=${{ inputs.notifyTesters }}
        export INPUT_DEBUG=${{ inputs.debug }}
        install-appcenter-cli.sh
        upload-to-appcenter.sh
      shell: bash
